# Generated by Django 6.0.4 on 2026-04-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of this resource', max_length=200)),
                ('description', models.TextField(help_text='A brief description of what this resource teaches')),
                ('url', models.URLField(blank=True, help_text='Web link (optional)', null=True)),
                ('category', models.CharField(choices=[('branching', 'Branching Strategies'), ('commits', 'Commit Conventions'), ('collaboration', 'Collaboration Practices'), ('tools', 'Git Tools & Commands'), ('general', 'General Git Knowledge')], default='general', max_length=50)),
                ('is_official', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Git Resource',
                'verbose_name_plural': 'Git Resources',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LearningNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('topic', models.CharField(choices=[('branching', 'Branching'), ('commits', 'Commits'), ('merging', 'Merging'), ('pull_requests', 'Pull Requests'), ('other', 'Other')], default='other', max_length=50)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Learning Note',
                'verbose_name_plural': 'Learning Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
